# Generated by Django 5.2.7 on 2025-11-12 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_redactor_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "Newspaper",
                "verbose_name_plural": "Newspapers",
            },
        ),
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "Redactor", "verbose_name_plural": "Redactors"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "Topic", "verbose_name_plural": "Topics"},
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="year_of_experience",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ]
            ),
        ),
    ]
